name = "alfredflix"
compatibility_date = "2024-12-01"
compatibility_flags = [
  "nodejs_compat",
  "experimental"
]

[env.production]
vars = { NODE_ENV = "production" }

# For database, you'll need to set up Cloudflare D1 or use an external PostgreSQL
# Uncomment and configure if using D1:
# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "alfredflix-db"
# database_id = "your-d1-database-id"

# Environment variables (set via wrangler secret)
# DATABASE_URL
# STRIPE_SECRET_KEY  
# VITE_STRIPE_PUBLIC_KEY
# MAILGUN_API_KEY
# MAILGUN_DOMAIN
# MAILGUN_FROM_EMAIL